-- Gela Fácil - schema inicial para Supabase (PostgreSQL)
-- Execute este arquivo no SQL Editor de um projeto Supabase novo.

begin;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  brand text not null,
  name text not null,
  category text not null,
  price numeric(12, 2) not null default 0,
  old_price numeric(12, 2),
  stock integer not null default 0,
  min_stock integer not null default 3,
  sku text,
  specs text,
  status text not null default 'active',
  image text,
  affiliate_url text,
  mercado_livre_id text,
  description text,
  gallery jsonb not null default '[]'::jsonb,
  source_attributes jsonb not null default '{}'::jsonb,
  rating numeric(3, 2) not null default 0,
  rating_count integer not null default 0,
  reviews jsonb not null default '[]'::jsonb,
  source_status text,
  source_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint products_brand_not_blank check (btrim(brand) <> ''),
  constraint products_name_not_blank check (btrim(name) <> ''),
  constraint products_category_check check (
    category in ('inverter', 'split', 'portatil', 'bebidas')
  ),
  constraint products_price_check check (price >= 0),
  constraint products_old_price_check check (old_price is null or old_price >= 0),
  constraint products_stock_check check (stock >= 0),
  constraint products_min_stock_check check (min_stock >= 0),
  constraint products_status_check check (status in ('active', 'inactive')),
  constraint products_mercado_livre_id_check check (
    mercado_livre_id is null or mercado_livre_id ~ '^MLB[0-9]{6,}$'
  ),
  constraint products_rating_check check (rating >= 0 and rating <= 5),
  constraint products_rating_count_check check (rating_count >= 0),
  constraint products_gallery_check check (jsonb_typeof(gallery) = 'array'),
  constraint products_source_attributes_check check (jsonb_typeof(source_attributes) = 'object'),
  constraint products_reviews_check check (jsonb_typeof(reviews) = 'array')
);

create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint admin_users_username_not_blank check (btrim(username) <> ''),
  constraint admin_users_password_hash_not_blank check (btrim(password_hash) <> '')
);

create index if not exists products_public_catalog_idx
  on public.products (status, id desc);

create index if not exists products_category_idx
  on public.products (category);

create index if not exists products_sku_idx
  on public.products (sku)
  where sku is not null and btrim(sku) <> '';

create unique index if not exists products_mercado_livre_id_idx
  on public.products (mercado_livre_id)
  where mercado_livre_id is not null;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row
execute function public.set_updated_at();

drop trigger if exists admin_users_set_updated_at on public.admin_users;
create trigger admin_users_set_updated_at
before update on public.admin_users
for each row
execute function public.set_updated_at();

alter table public.products enable row level security;
alter table public.admin_users enable row level security;

-- O navegador nunca acessa as tabelas diretamente. O backend valida a sessão
-- administrativa e usa a service role, que ignora RLS.
revoke all on table public.products from anon, authenticated;
revoke all on sequence public.products_id_seq from anon, authenticated;
revoke all on table public.admin_users from anon, authenticated;
revoke all on sequence public.admin_users_id_seq from anon, authenticated;

comment on table public.products is
  'Catálogo e estoque da vitrine Gela Fácil, administrados exclusivamente pelo backend.';

comment on table public.admin_users is
  'Administradores do painel. Senhas são armazenadas somente como hash bcrypt.';

-- Bucket usado por POST /api/admin/upload. A leitura é pública para que as
-- imagens apareçam na vitrine; gravações continuam restritas à service role.
insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'products',
  'products',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']::text[]
)
on conflict (id) do update
set
  name = excluded.name,
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

commit;
