const fs = require('fs');
const path = require('path');
const vm = require('vm');
const assert = require('node:assert/strict');
const projectRoot = path.resolve(__dirname, '..');
const elements = new Map();
const get = id => {
 if (!elements.has(id)) elements.set(id, { value: '', textContent: '', innerHTML: '', style: {}, hidden: false, disabled: false, listeners: {}, setAttribute() {}, removeAttribute() {}, addEventListener(type, fn) { this.listeners[type] = fn; }, querySelector() { return get(id + '-child'); } });
 return elements.get(id);
};
const context = vm.createContext({ document: { getElementById: get, addEventListener() {} }, window: { location: { hostname: 'localhost', port: '3000' } }, console, setTimeout, fetch: async () => ({ok:true,json:async()=>[]}) });
vm.runInContext(fs.readFileSync(path.join(projectRoot, 'admin', 'admin.js'),'utf8'), context);
for (const id of ['product-category-filter','product-status-filter']) get(id).value='all';
get('product-sort').value='name';
vm.runInContext(`DB.products = [
 {id:1,name:'Ar <teste>',brand:'Marca',sku:null,category:'split',price:123.45,status:'active',image:'assets/test.png',gallery:[],affiliateUrl:'https://mercadolivre.com/sec/teste'},
 {id:2,name:'Outro',brand:'Marca',sku:'SKU2',category:'split',price:22,status:'inactive',image:'',gallery:[]}
]; renderProducts();`,context);
assert.equal(get('summary-total').textContent,2);
assert.equal(get('summary-active').textContent,1);
assert.equal(get('summary-inactive').textContent,1);
assert.match(get('products-body').innerHTML,/Ar &lt;teste&gt;/);
assert.match(get('products-body').innerHTML,/src="\/assets\/test.png"/);
assert.match(get('products-body').innerHTML,/123,45/);
assert.match(get('products-body').innerHTML,/Abrir link de afiliado/);
get('product-status-filter').value='inactive';
vm.runInContext('renderProducts()',context);
assert.equal(get('products-pagination').textContent,'1 de 2 produtos');
get('product-search').value='nonexistent';
vm.runInContext('renderProducts()',context);
assert.match(get('products-body').innerHTML,/Nenhum produto encontrado/);
(async()=>{
 get('prod-gallery').value='assets/foto-2.webp\nassets/foto-2.webp\nassets/foto-3.webp';
 const gallery=await vm.runInContext("buildProductGallery('assets/principal.webp')",context);
 assert.equal(JSON.stringify(gallery),JSON.stringify(['assets/principal.webp','assets/foto-2.webp','assets/foto-3.webp']));
 context.window.location={hostname:'127.0.0.1',port:'8000'};
 context.fetch=async()=>({ok:true,status:200,headers:{get:()=> 'text/html; charset=utf-8'}});
 await assert.rejects(vm.runInContext("apiFetch('/api/admin/products')",context),/prévia não está conectada à API/);
 context.window.location={hostname:'localhost',port:'3000'};
 context.fetch=async()=>{throw Error('offline');};
 await vm.runInContext('refreshCatalog()',context);
 assert.equal(get('retry-products').hidden,false);
 assert.match(get('catalog-feedback-child').textContent,/offline/);
 context.fetch=async()=>({ok:true,json:async()=>[]});
 await vm.runInContext('refreshCatalog()',context);
 assert.equal(get('catalog-feedback').hidden,true);
 let calls=0, finish;
 context.save = () => { calls++; return new Promise(resolve=>{finish=resolve;}); };
 vm.runInContext("bindBusyForm('test-form', save)",context);
 const submit=get('test-form').listeners.submit;
 const pending=submit({preventDefault(){}});
 await submit({preventDefault(){}});
 assert.equal(calls,1); assert.equal(get('test-form-child').disabled,true);
 finish(); await pending;
 assert.equal(get('test-form-child').disabled,false);
 const html=fs.readFileSync(path.join(projectRoot, 'admin', 'index.html'),'utf8');
 const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
 assert.equal(new Set(ids).size,ids.length,'Duplicate HTML ids');
 assert.ok(!html.includes('page-orders'));
 assert.ok(!/estoque|stock/i.test(html),'Admin HTML should not expose stock controls');
 assert.ok(ids.includes('prod-gallery-files') && ids.includes('prod-gallery'));
 assert.ok(ids.includes('prod-affiliate-url'));
 for(const match of html.matchAll(/<label for="([^"]+)"/g)) assert.ok(ids.includes(match[1]));
 console.log('PASS: summary, filters, escaping, images, currency, gallery, stock removal, API failure/retry, duplicate submit prevention, HTML ids and labels.');
})().catch(error=>{console.error(error);process.exitCode=1;});
