create table if not exists public.products (
  id bigint generated by default as identity primary key,
  brand text not null,
  name text not null,
  category text not null,
  price numeric(12, 2) not null default 0,
  old_price numeric(12, 2),
  stock integer not null default 0,
  min_stock integer not null default 3,
  sku text,
  specs text,
  status text not null default 'active' check (status in ('active', 'inactive')),
  image text,
  affiliate_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Compatibilidade com bancos criados antes do link de afiliado.
alter table public.products add column if not exists affiliate_url text;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row
execute function public.set_updated_at();

alter table public.products enable row level security;

-- Nenhum cliente do Supabase recebe permissao direta nesta tabela.
-- O backend usa a service role somente no servidor, apos validar a sessao administrativa.
revoke all on table public.products from anon, authenticated;
revoke all on sequence public.products_id_seq from anon, authenticated;
