-- Execute esta migração no SQL Editor se o schema inicial já foi aplicado.

begin;

create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint admin_users_username_not_blank check (btrim(username) <> ''),
  constraint admin_users_password_hash_not_blank check (btrim(password_hash) <> '')
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists admin_users_set_updated_at on public.admin_users;
create trigger admin_users_set_updated_at
before update on public.admin_users
for each row
execute function public.set_updated_at();

alter table public.admin_users enable row level security;

revoke all on table public.admin_users from anon, authenticated;
revoke all on sequence public.admin_users_id_seq from anon, authenticated;

comment on table public.admin_users is
  'Administradores do painel. Senhas são armazenadas somente como hash bcrypt.';

commit;
